// https://www.online-utility.org/text/sort.jsp
// https://alphabetizer.flap.tv/
module.exports = [
	"300",
	"Afternoon Delight",
	"Bachy West XC",
	"Ben's",
	"Black Rock",
	"Bushwhacking",
	"COD Rockstacker",
	"COD",
	"Catch & Release",
	"Crazyhorse", // Horse Ridge
	"Crooked Arm", // Horse Ridge
	"DRT",
	"Dinah Moe Humm",
	"Dry River Canyon", // Horse Ridge
	"Duodenum",
	"ELV",
	"EXT",
	"Edison Sno Park",
	"Edison-Lava",
	"Elko Point",
	"Escape from Moscow", // Horse Ridge
	"Expressway",
	"Farewell",
	"Flagline Access",
	"Flagline Tie",
	"Flagline",
	"Funner",
	"Grand Slam",
	"Has No Horse", // Horse Ridge
	"Helipad",
	"Holy Loop", // Horse Ridge
	"Horse Butte",
	"Horse Ridge",
	"KGB",
	"Kent's",
	"Kiwa Butte",
	"Larsen's",
	"Lone Wolf",
	"Lower Whoops",
	"MTB",
	"Mad Max Drive", // Horse Ridge
	"Marvin's Garden",
	"Metolius-Windigo",
	"Mrazek",
	"NF-4610",
	"NF-4615/Swede Rd",
	"Northfork",
	"Old Dirty Pirate",
	"Parkway", // Horse Ridge
	"Phil's",
	"Pinedrops",
	"Ridge Loop",
	"Roundabout",
	"S.S.T.",
	"SST",
	"Sand Canyon", // Horse Ridge
	"Sector 16",
	"Shevlin Park",
	"Skyliner",
	"Southfork",
	"Storm King",
	"Swamp Wells",
	"Swampy",
	"Swampy/Dutchman",
	"Swan Song",
	"Swede Ridge",
	"Tetherow Connector",
	"Ticket to Ride",
	"Tiddlywinks",
	"Tumalo Creek",
	"Tumalo Ridge",
	"Tumalo Tie",
	"Tyler's Traverse",
	"Unknown",
	"Upper Whoops",
	"Vista Butte",
	"VooDoo Child",
	"VooDoo",
	"Waldo Lake", // Oakridge
];